# Retail Store Sales Analysis
## Data Cleaning Using Python

In [10]:
import pandas as pd
import numpy as np

## Load the Dataset

In [16]:
df = pd.read_csv("G:\\My Drive\\MAIN PROJECT(ENTRI)\\Retailstore_Sales_cleaned.csv")
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,08-04-2024,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,23-07-2023,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,05-10-2022,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,07-05-2022,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,02-10-2022,False

## Dataset Information

Understand dataset size, column types, missing values, and basic statistics.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

## Data Quality Checks


### Missing values:

#### 1.Missing data can affect statistical calculations and model performance
#### 2.Need to identify which columns have missing values
#### 3.This helps to plan appropriate handling strategies

### Duplicate rows:


#### 1.Duplicate records can twist analysis result
#### 2.They may indicatedata entry errors
#### 3.Duplicate should be removed to ensure data integrity

In [5]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

## Handle Missing Values

Ensure accurate calculations by removing or filling missing data.

In [12]:
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Price Per Unit'].mean())
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())
df['Total Spent'] = df['Total Spent'].fillna(df['Total Spent'].mean())
df['Item'] = df['Item'].fillna(df['Item'].mode()[0])
df['Discount Applied'] = df['Discount Applied'].fillna('False')

## Convert Transaction Date to Datetime

The purpose of converting Transaction Date to datetime is to enable accurate time-based analysis, such as monthly and yearly sales trends, and to perform date-related calculations correctly.

In [20]:
df['Transaction date']=pd.to_datetime(df['Transaction date'],errors='coerce')
df['Year'] = df['Transaction Date'].dt.year
df['Month'] = df['Transaction Date'].dt.month

## Convert Discount Applied to Boolean

converting Discount Applied to Boolean is to simplify analysis by clearly indicating whether a discount was applied (True) or not (False), making it easier to analyze its impact on sales and customer behavior

In [8]:
df ['Discount Applied'].unique()
df['Discount Applied'] = False
df['Discount Applied'] = df['Discount Applied'].astype(bool)
df['Discount Applied'].unique()
df.dtypes

Transaction ID       object
Customer ID          object
Category             object
Item                 object
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
Discount Applied       bool
dtype: object

## Remove Duplicates Records

In [21]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [22]:
df.duplicated().sum()

np.int64(0)

## Final Dataset Check

•	Ensure dataset is clean, complete, and ready for EDA

•	Confirm no missing values, no duplicates, correct data types

•	Validate that date, numeric, and categorical columns are accurate for analysis

In [7]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              12575 non-null  object
 4   Price Per Unit    12575 non-null  float64
 5   Quantity          12575 non-null  float64
 6   Total Spent       12575 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  12575 non-null  object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,08-04-2024,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,23-07-2023,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,05-10-2022,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,07-05-2022,False
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,02-10-2022,False

## Save Cleaned Dataset

In [5]:
df .to_csv("G:\\My Drive\\MAIN PROJECT(ENTRI)\\Retailstore_Sales_cleaned.csv",index=False)
print("Final cleaned dataset saved successfully")

Final cleaned dataset saved successfully